name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy_to_prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: .
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN1 }}
